# -------------------------------------------------------------------------------------
# The following is a necessary configuration for the FixIt theme.
# -------------------------------------------------------------------------------------

title = "Brian's Homepage"
baseURL = "https://brian-sinquin.github.io/"
# Change the default theme to be use when building the site with Hugo
theme = "FixIt"
